apiVersion: v1
kind: Template
labels:
  template: routetemplate
metadata:
  annotations:
    description: Generic Route Template for setting up projects in OCP
    tags: routetemplate
    name: routetemplate
  name: routetemplate
objects:
- apiVersion: v1
  id: ${APP_NAME}-https
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service.
    labels:
      app: ${APP_NAME}
      maker: cicd-pipeline
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    tls:
      termination: edge
    to:
      name: ${APP_NAME}

parameters:
- name: APP_NAME
  description: "Name of the deployable application."
  displayName: "Application Name"
  required: true
- name: APP_NAMESPACE
  description: "Name of the project namespace where the build will reside."
  displayName: "Application Namespace"
  required: true
