apiVersion: v1
kind: Template
labels:
  template: stevetemplate
metadata:
  annotations:
    description: Generic ODFL Application Template for setting up projects in OCP
    tags: java,springboot
    name: stevetemplate
  namespace: project-steve-dev
  name: stevetemplate
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: This is a service :)
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APP_NAME}
- apiVersion: v1
  id: ${APP_NAME}-https
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service.
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    tls:
      termination: edge
    to:
      name: ${APP_NAME}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentConfig: ${APP_NAME}
        name: ${APP_NAME}
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: ${CONFIG_MAP_REF}
          - secretRef:
              name: ${SECRET_KEY_REF}
          image: ${APP_NAME}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: ${LIVELINESS_PROBE}
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          name: ${APP_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: ${READINESS_PROBE}              
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
          namespace: ${APP_NAMESPACE}
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    failedBuildsHistoryLimit: 10
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:${IMAGE_TAG}
    runPolicy: Serial
    source:
      type: None
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: ${BASE_IMAGE}
          namespace: ${IMAGE_STREAM_NAMESPACE}
    successfulBuildsHistoryLimit: 10
    triggers: []

- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    lookupPolicy:
      local: false

parameters:
- name: APP_NAME
  value: name-of-application
  description: "Name of the deployable application."
  displayName: "Application Name"
  required: true
- name: APP_NAMESPACE
  value: some-namespace
  description: "Name of the project namespace where the build will reside."
  displayName: "Application Namespace"
  required: true
- name: IMAGE_STREAM_NAMESPACE
  value: project-steve-dev
  description: "Name of the project namespace where the image streams reside."
  displayName: "ImageStream Namespace"
  required: false
- name: MEMORY_LIMIT
  value: 512Mi
  description: Container memory limit.
  displayName: Container Memory Limit
  required: false
- name: BASE_IMAGE
  value: redhat-openjdk-18:latest
  description: Base image name.
  displayName: Base Image Name
  required: false
- name: CONFIG_MAP_REF
  description: "Name of the config map reference."
  displayName: "Config Map Reference"
  required: true
- name: SECRET_KEY_REF
  description: "Name of the secret key reference."
  displayName: "Secret Key Reference"
  required: true
- name: LIVELINESS_PROBE
  description: "Liveliness probe http endpoint to check."
  displayName: "Liveliness Probe URL"
  required: true
- name: READINESS_PROBE
  description: "Readiness probe http endpoint to check."
  displayName: "Readiness Probe URL"
  required: true
- name: IMAGE_TAG
  value: latest
  description: "The Tag name to apply to the built application image"
  displayName: "Image Tag"
  required: false
